print('Введите координаты двух точек')
x1 = int(input('Введите x1:'))
y1 = int(input('Введите y1:'))
x2 = int(input('Введите x2:'))
y2 = int(input('Введите y2:'))
print(f'{y1 - y2}*x+{x2 - x1}*y+{x1 * y2 - x2 * y1}=0')
